[greenclip]
  blacklisted_applications = []
  enable_image_support = true
  history_file = "/home/dave/.cache/greenclip.history"
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 50
  max_selection_size_bytes = 0
  static_history = ['==== PINNED ====','sf project generate manifest --metadata ApexClass:REST_Donation ApexClass:REST_DonationTest ApexTrigger:paymentOpportunity','sf project deploy start --manifest package.xml --test-level RunSpecifiedTests --tests processPaymentTest REST_DonationTest --target-org "Greenham Prod"','sf project deploy start --manifest ./destroy/package.xml --pre-destructive-changes ./destroy/destructiveChanges.xml --target-org "Greenham Prod"','sf project generate manifest --output-dir destroy  --metadata ApexClass:GDGC_DonationController ApexClass:GDGC_DonationControllerTest ApexPage:GDGC_Participant --type destroy','git commit --amend --no-edit','config push git@github-personal:davecburke/dotfiles.git','brscan-skey','python3 -m http.server','sf sfdmu run --sourceusername "aakonsult@greenham.com.au" --targetusername "aakonsult@greenham.com.au.dbsandbox"']  
  trim_space_from_selection = true
  use_primary_selection_as_input = false
